Create README_AR.rtl.md
zksync/credo pull request #54
Opened 2023-11-08 17:34 UTC by 0xObsidian

README supported in Arabic

2023-11-08 17:48 UTC, RamanSB requested changes

2023-11-08 17:48 UTC, RamanSB commented on README_AR.rtl.md
> +
```suggestion
Remove line...
```

2023-11-08 17:48 UTC, RamanSB requested changes

2023-11-08 17:48 UTC, RamanSB commented on README_AR.rtl.md
> +
```suggestion
```

2023-11-08 17:48 UTC, RamanSB commented on README_AR.rtl.md
> +
Line removal

2023-11-24 10:06 UTC, 0xsisyfos commented
Hello @0xObsidian 

First of all, thank you very much for contributing to the ZK Credo by translating it. We appreciate it greatly, and the community will benefit immensely from your work.

To ensure the quality and consistency of the ZK Credo, we asked a third party to review the translation. We invite you to consider their feedback and make the necessary changes before we accept the PR. Please find the suggestions below. 

<img width="541" alt="Screenshot 2023-11-24 at 11 05 31" src="https://github.com/zksync/credo/assets/107465625/2ed3210b-4466-4b0e-bfba-df0b691092a4">

Let me know if you have any comments on the suggestions above.

2023-11-25 20:54 UTC, 0xObsidian commented
Changes implemented thank you

2023-11-26 22:53 UTC, merged